name: build
permissions:
  contents: read
  pull-requests: read

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: actions/setup-go@v6
      with:
        go-version: stable

    - name: Install OpenGL
      run: sudo apt-get update && sudo apt-get install -y xorg-dev mesa-utils libgl1 libgl1-mesa-dev

    - name: Build
      run: |
        go mod vendor
        git status
        GOOS=linux GOARCH=amd64 go build
